### ISSUE TITLE
ClassififcationDataset存在错误

### ISSUE THREAD

**Issue by JUNXYU** [HiLab-git/PyMIC#14]
王老师，您好，在ClassificationDataset定义中，读取数据权重时是不是存在错误

if self.image_weight_idx is not None:
        sample["image_weight"] = self.__getweight__(idx)

但是您并没有定义self.__getweight__。而是重写了self.__get_pixel_weight__
是不是应该将self.__getweight__(idx)修改为self.__get_pixel_weight__(idx

**Comment by taigw** [comment]
@JUNXYU, 是的，代码中写错了，应在ClassificationDataset定义中将 __get_pixel_weight__函数的名字写成__getweight__
