### ISSUE TITLE
Relationship with the PyMIC example

### ISSUE THREAD

**Issue by qiyedongcode** [HiLab-git/PyMIC#28]
There is no config file found here, which is different from the example. How can I use this project to train my own dataset and where should the dataset be placed

**Comment by taigw** [comment]
Please go to PyMIC_example (https://github.com/HiLab-git/PyMIC_examples) to find some examples to use PyMIC. If you have run some segmentation examples, you should know how to put your data. Actually, you can put you data anywhere on your disk, and just need to set ''data_root'' in the configuration file.
