### ISSUE TITLE
Typo of `num_worker`

### ISSUE THREAD

**Issue by billzhonggz** [HiLab-git/PyMIC#30]
In the following lines, the config key `num_workder` looks like a typo of `num_worker`. This leads to a key error when reading the config files.

Please consider fixing it. Thanks!

https://github.com/HiLab-git/PyMIC/blob/a114a79ef35feb1097b98cdc09deb6700d612718/pymic/net_run/agent_abstract.py#L262

https://github.com/HiLab-git/PyMIC/blob/a114a79ef35feb1097b98cdc09deb6700d612718/pymic/net_run_nll/nll_dast.py#L159

https://github.com/HiLab-git/PyMIC/blob/a114a79ef35feb1097b98cdc09deb6700d612718/pymic/net_run_ssl/ssl_abstract.py#L76

**Comment by taigw** [comment]
Thanks, this has been fixed in the latest version of the dev branch.
