### ISSUE TITLE
error in image_convert

### ISSUE THREAD

**Issue by manjusaka999** [HiLab-git/PyMIC#8]
Dear author:
 When I have configured the environment as required and put relevant documents in place，I run image_convert.py,but when it goes to JPCLN120.IMG or JPCLN121.IMG,it will goes wrong:
`Traceback (most recent call last):`
  `File "***/PyMIC-master/examples/JSRT/image_convert.py", line 63, in <module>`
   ` convert_JCRT_images(input_image_dir, output_image_dir)`
  `File "***/PyMIC-master/examples/JSRT/image_convert.py", line 21, in convert_JCRT_images`
  `  data = data.reshape(shape)`
`ValueError: cannot reshape array of size 4130214 into shape (2048,2048)`
 I have no idea about this. Could you please give me a solution or suggestion？
Best wishes!

**Comment by taigw** [comment]
@manjusaka999 , the example has now been moved to https://github.com/HiLab-git/PyMIC_examples/tree/main/segmentation/JSRT
